### ISSUE TITLE
Periods seem to be treated as placeholder characters?

### ISSUE THREAD

**Issue by mhmdanas** [termux/command-not-found#7]
Sorry if this is mentioned somewhere, but I failed to find anything about this, and my C++ knowledge is nil.

Try running `..` for instance (it will show all commands with two characters or less). It works with `...` too, but trying four periods and longer seems to not show the "did you mean" thing for some reason. This also works with other characters (e.g. try running `p.thon`); it reminds me of regexes.

Is this intended behavior? If so, it would be great if it was documented, I can imagine it being useful.

**Comment by Grimler91** [comment]
It's not a placeholder character. It just so happens that `.` is not part of any command, so running `..` could literally be any 2 char command. You get the same behaviour if you run for example `::` or any other character that isn't part of known commands.

> trying four periods and longer seems to not show the "did you mean" thing for some reason

That's because it only reports commands where the [levenshtein distance is 3 or less](https://github.com/termux/command-not-found/blob/master/command-not-found.cpp#L182)

**Comment by Grimler91** [comment]
All characters is a placeholder character in some sense, that's how the algorithm works, it just checks character for character. See https://en.wikipedia.org/wiki/Levenshtein_distance

**Comment by mhmdanas** [comment]
Ah, thanks, that clears things up. Sorry for the noise.
